function HowItWorks() {
  return (
    <div className="how-it-works flex flex-col md:flex-row justify-center align-center">
      <div className="flex flex-col justify-center md:w-3/4">
        <div className="text-center mb-8 text-2xl font-extrabold leading-none tracking-tight text-red-500 md:text-3xl lg:text-4xl">
          How it works
        </div>
        <div className="text-center hidden md:block mb-4 text-lg font-extrabold leading-none tracking-tight text-gray-700 md:text-lg lg:text-lg">
          Experience the power of AI for instant, accurate, and free academic
          assistance.
        </div>
      </div>
      <ol className="relative border-l border-red-300">
        <li className="mb-10 ml-4">
          <div className="absolute w-3 h-3 bg-red-400 rounded-full mt-1.5 -left-1.5 border border-white "></div>
          <time className="mb-1 text-sm font-normal leading-none text-red-500">
            Step 1
          </time>
          <h3 className="text-lg font-semibold text-gray-900">
            Upload your document/question
          </h3>
          <p className="mb-4 text-base font-normal text-gray-500">
            Get Questions: The system will extract questions from your document
            and show them to you for review.
          </p>
        </li>
        <li className="mb-10 ml-4">
          <div className="absolute w-3 h-3 bg-red-400 rounded-full mt-1.5 -left-1.5 border border-white"></div>
          <time className="mb-1 text-sm font-normal leading-none text-red-500">
            Step 2
          </time>
          <h3 className="text-lg font-semibold text-gray-900">
            Review your questions
          </h3>
          <p className="text-base font-normal text-gray-500">
            The extracted questions will be shown to you for review.
          </p>
        </li>
        <li className="mb-10 ml-4">
          <div className="absolute w-3 h-3 bg-red-400 rounded-full mt-1.5 -left-1.5 border border-white"></div>
          <time className="mb-1 text-sm font-normal leading-none text-red-500">
            Step 3
          </time>
          <h3 className="text-lg font-semibold text-gray-900">
            Generate Answers
          </h3>
          <p className="text-base font-normal text-gray-500">
            The system will generate answers to the questions.
          </p>
        </li>
        <li className="mb-10 ml-4">
          <div className="absolute w-3 h-3 bg-red-400 rounded-full mt-1.5 -left-1.5 border border-white"></div>
          <time className="mb-1 text-sm font-normal leading-none  text-red-500">
            Step 4
          </time>
          <h3 className="text-lg font-semibold text-gray-900">
            Review Answers
          </h3>
          <p className="text-base font-normal text-gray-500">
            You can correct the answers generated by the system.
          </p>
        </li>
        <li className="ml-4">
          <div className="absolute w-3 h-3 bg-red-400 rounded-full mt-1.5 -left-1.5 border border-white"></div>
          <time className="mb-1 text-sm font-normal leading-none  text-red-500">
            Step 5
          </time>
          <h3 className="text-lg font-semibold text-gray-900">Download</h3>
          <p className="text-base font-normal text-gray-500">
            Once you have corrected the answers you can download the answers as
            PDF.
          </p>
        </li>
      </ol>
    </div>
  );
}

export default HowItWorks;
